#!/usr/bin/env python3
"""Generate the CSO Spillcast Jekyll pages from the published manifest.

Reads `manifest.json` (published to S3 by the cso_lstm forecast deployment's
publish_s3.py) and writes, into this website repo:

  _data/cso_spillcast.json        — CSO list driving the TOC table
  _pages/cso_spillcast/{slug}.md  — one stub page per CSO (uses the shared
                                    _includes/spillcast-page.html template)

Stale stubs (CSOs no longer in the manifest) are removed. The TOC page
(_pages/cso_spillcast.md) and the template (_includes/spillcast-page.html) are
hand-maintained and NOT touched by this script.

Run this only when the CSO set changes or after retraining, then commit & push:

    python tools/build_spillcast_pages.py
    git add _data/cso_spillcast.json _pages/cso_spillcast
    git commit -m "Update CSO Spillcast pages" && git push

Standard library only — no dependencies needed.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

DEFAULT_MANIFEST_URL = (
    "https://alexlipp-cso-spillcast.s3.eu-west-2.amazonaws.com/cso_spillcast/manifest.json"
)

REPO_ROOT = Path(__file__).resolve().parent.parent
PAGES_DIR = REPO_ROOT / "_pages" / "cso_spillcast"
DATA_FILE = REPO_ROOT / "_data" / "cso_spillcast.json"


def _fetch_manifest(url: str) -> dict:
    if url.startswith(("http://", "https://")):
        print(f"Fetching manifest: {url}")
        with urllib.request.urlopen(url) as resp:  # noqa: S310 (trusted URL)
            return json.loads(resp.read().decode())
    # Allow a local file path for testing / offline use.
    print(f"Reading manifest from file: {url}")
    return json.loads(Path(url).read_text())


def _fm(value) -> str:
    """Encode a scalar as a YAML front-matter value (JSON is valid YAML)."""
    return json.dumps(value)


def _write_stub(cso: dict) -> None:
    permit = cso["permit"]
    slug = cso["slug"]
    title = f"CSO Spillcast — {cso['name']} ({permit})"
    metrics = cso.get("metrics") or {}

    lines = [
        "---",
        "# AUTO-GENERATED by tools/build_spillcast_pages.py — do not edit by hand.",
        f"title: {_fm(title)}",
        f"permalink: /cso_spillcast/{slug}/",
        "author_profile: false",
        f"permit: {_fm(permit)}",
        f"cso_name: {_fm(cso['name'])}",
        f"plot_url: {_fm(cso['plot_url'])}",
        f"csv_url: {_fm(cso['csv_url'])}",
        f"reliability_url: {_fm(cso['reliability_url'])}",
        f"f1: {_fm(metrics.get('f1'))}",
        f"pr_auc: {_fm(metrics.get('pr_auc'))}",
        f"auc: {_fm(metrics.get('auc'))}",
        f"brier_skill: {_fm(metrics.get('brier_skill'))}",
        "---",
        "{% include spillcast-page.html %}",
        "",
    ]
    (PAGES_DIR / f"{slug}.md").write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest-url", default=DEFAULT_MANIFEST_URL,
                    help="Manifest URL (or local file path for testing).")
    args = ap.parse_args()

    manifest = _fetch_manifest(args.manifest_url)
    csos = manifest.get("csos", [])
    if not csos:
        sys.exit("Manifest contains no CSOs — nothing to generate.")

    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)

    # TOC data (compact list for the Jekyll loop).
    toc = [{"permit": c["permit"], "slug": c["slug"], "name": c["name"]} for c in csos]
    DATA_FILE.write_text(json.dumps(toc, indent=2) + "\n")
    print(f"  ✓ {DATA_FILE.relative_to(REPO_ROOT)}  ({len(toc)} CSOs)")

    # Per-CSO stub pages.
    wanted = set()
    for cso in csos:
        _write_stub(cso)
        wanted.add(cso["slug"])
        print(f"  ✓ _pages/cso_spillcast/{cso['slug']}.md")

    # Remove stale stubs for CSOs no longer in the manifest.
    for existing in PAGES_DIR.glob("*.md"):
        if existing.stem not in wanted:
            existing.unlink()
            print(f"  ✗ removed stale {existing.name}")

    print("\n✓ Done. Review, then commit & push the website repo.")


if __name__ == "__main__":
    main()
